#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

#hello_page:
 # path: /

  #controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  #defaults:
   # template: 'hello_page.html.twig'
